plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@codedependant/semantic-release-docker"
    - dockerLogin: false
      dockerArgs:
        PHP_VERSION: '{{env.PHP_VERSION}}'
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"
