name: build php
on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
env:
  IMAGE_NAME: ${{ github.repository }}
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [ '8.0', '8.1', '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --tags
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=false
            type=ref,event=pr
            type=raw,value=${{ matrix.php_version }}
            type=semver,pattern=${{ matrix.php_version }}-{{version}}
            type=semver,pattern=${{ matrix.php_version }}-{{major}}
            type=semver,pattern=${{ matrix.php_version }}-{{major}}.{{minor}}
      - name: Publish
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
