name: php 7.4
on:
  push:
    tags:
      - 'v*'
env:
  IMAGE_NAME: ${{ github.repository }}
  PHP_VERSION: '7.4'
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=false
            type=ref,event=branch
            type=ref,event=pr
            type=raw,pattern=${{ env.PHP_VERSION }}
            type=semver,pattern=${{ env.PHP_VERSION }}-{{version}}
            type=semver,pattern=${{ env.PHP_VERSION }}-{{major}}
            type=semver,pattern=${{ env.PHP_VERSION }}-{{major}}.{{minor}}
      - name: Publish
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
